name:  tic_development
description:  development framework for tic.
version: 0.0.2
author: Sam E. <same@nanosn.com>
homepage: https://github.com/NanoSN/tic-development

dependencies:
  pathos: any
  mimetypes: any
dev_dependencies:
  unittest: any
